export enum ErrorCode {
    UNAUTHORIZED = 'UNAUTHORIZED',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_PAYLOAD = 'INVALID_PAYLOAD',
    FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR',
    NOT_FOUND = 'NOT_FOUND',
    FORBIDDEN = 'FORBIDDEN',
    INTERNAL_ERROR = 'INTERNAL_ERROR',
}
